<?xml version="1.0" encoding="UTF-8"?>
<source package="org.apache.commons.math3">
  <import name="java.util.Random" />
  <import name="org.apache.commons.math3.exception.MathIllegalStateException" />
  <import name="org.junit.Test" />
  <import name="org.junit.runner.RunWith" />
  <class name="RetryRunnerTest" startLine="27">
    <javadoc>
      <text>* Test for the "Retry" functionality (retrying Junit test methods).</text>
    </javadoc>
    <declaration type="Random" name="rng" />
    <javadoc>
      <text>* Shows that an always failing test will fail even if it is retried.</text>
    </javadoc>
    <method type="void" name="testRetryFailAlways" startLine="39" endLine="41" />
    <javadoc>
      <text>* Shows that a test that sometimes fail might succeed if it is retried.
 * In this case the high number of retries makes it quite unlikely that
 * the exception will be thrown by all of the calls.</text>
    </javadoc>
    <method type="void" name="testRetryFailSometimes" startLine="50" endLine="54">
      <scope startLine="51" endLine="53" />
    </method>
  </class>
</source>
