<?xml version="1.0" encoding="UTF-8"?>
    <source package="javax.naming.event">
        <import package="javax.naming.NamingException"/>
        <class name="NamingExceptionEvent" line="30">
            <extends class="java.util.EventObject"/>
            <javadoc line="30">
                This class represents an event fired when the procedures/processes
                  used to collect information for notifying listeners of
                  &lt;tt&gt;NamingEvent&lt;/tt&gt;s threw a &lt;tt&gt;NamingException&lt;/tt&gt;.
                  This can happen, for example, if the server which the listener is using
                  aborts subsequent to the &lt;tt&gt;addNamingListener()&lt;/tt&gt; call.                
                <author>
                    Rosanna Lee                    
                </author>
                <author>
                    Scott Seligman                    
                </author>
                <see>
                    NamingListener#namingExceptionThrown                    
                </see>
                <see>
                    EventContext                    
                </see>
                <since>
                    1.3                    
                </since>
            </javadoc>
            <declaration name="exception" type="NamingException" line="46"/>
            <javadoc line="46">
                Contains the exception that was thrown                
                <serial>
                                        
                </serial>
            </javadoc>
            <javadoc line="52">
                Constructs an instance of &lt;tt&gt;NamingExceptionEvent&lt;/tt&gt; using
                  the context in which the &lt;tt&gt;NamingException&lt;/tt&gt; was thrown and the exception
                  that was thrown.                
                <param>
                    source The non-null context in which the exception was thrown.                    
                </param>
                <param>
                    exc    The non-null <tt>NamingException</tt> that was thrown.                    
                </param>
            </javadoc>
            <method name="NamingExceptionEvent" type="constructor" line="61">
                <params>
                    <param name="source" type="EventContext"/>
                    <param name="exc" type="NamingException"/>
                </params>
            </method>
            <javadoc line="66">
                Retrieves the exception that was thrown.                
                <return>
                    The exception that was thrown.                    
                </return>
            </javadoc>
            <method name="getException" type="NamingException" line="70"/>
            <javadoc line="74">
                Retrieves the &lt;tt&gt;EventContext&lt;/tt&gt; that fired this event.
                  This returns the same object as &lt;tt&gt;EventObject.getSource()&lt;/tt&gt;.                
                <return>
                    The non-null <tt>EventContext</tt> that fired this event.                    
                </return>
            </javadoc>
            <method name="getEventContext" type="EventContext" line="79"/>
            <javadoc line="83">
                Invokes the &lt;tt&gt;namingExceptionThrown()&lt;/tt&gt; method on
                  a listener using this event.                
                <param>
                    listener The non-null naming listener on which to invoke
                      the method.                    
                </param>
            </javadoc>
            <method name="dispatch" type="void" line="89">
                <params>
                    <param name="listener" type="NamingListener"/>
                </params>
            </method>
            <declaration name="serialVersionUID" type="long" line="93"/>
        </class>
    </source>