<?xml version="1.0" encoding="UTF-8"?>
    <source package="org.apache.commons.math3">
        <import package="java.util.Random"/>
        <import package="org.apache.commons.math3.exception.MathIllegalStateException"/>
        <import package="org.junit.Test"/>
        <import package="org.junit.runner.RunWith"/>
        <class name="RetryRunnerTest" line="6">
            <javadoc line="6">
                Test for the &quot;Retry&quot; functionality (retrying Junit test methods).                
            </javadoc>
            <declaration name="rng" type="Random" line="10"/>
            <javadoc line="11">
                Shows that an always failing test will fail even if it is retried.                
            </javadoc>
            <method name="testRetryFailAlways" type="void" line="14"/>
            <javadoc line="17">
                Shows that a test that sometimes fail might succeed if it is retried.
                  In this case the high number of retries makes it quite unlikely that
                  the exception will be thrown by all of the calls.                
            </javadoc>
            <method name="testRetryFailSometimes" type="void" line="22">
                <scope line="23"/>
            </method>
        </class>
    </source>